sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
env:
  global:
    - CRAN_REPO=https://cran.rstudio.com
matrix:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
    services:
      - xvfb
    r_binary_packages:
      - BH
    r_packages:
      - rgdal
      - rgeos
  - os: linux
    dist: xenial
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
    services:
      - xvfb
    r_binary_packages:
      - BH
      - dplyr
      - igraph
      - RSQlite
      - stringi
    after_success:
      - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
    r_packages:
      - covr
      - devtools
      - rgdal
      - rgeos
    r_github_packages:
      - jimhester/lintr
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - libxml2-dev
    services:
      - xvfb
    r: devel
    r_binary_packages:
      - BH
      - dplyr
      - igraph
      - RSQlite
      - stringi
    r_packages:
      - devtools
      - rgdal
      - rgeos
      - XML
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - libxml2
        - udunits
        update: true
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_script:
    - Rscript -e "install.packages(c('rgdal', 'rgeos', 'XML'), type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
